queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged
  - name: speculative
    conditions: []

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label=merge
    actions:
      queue:
        name: default
  - name: merge speculatively
    conditions:
      - base=master
      - label=speculative-merge
    actions:
      queue:
        name: speculative
