queue_rules:
  - name: speculative
    conditions: []

pull_request_rules:
  - name: merge speculatively
    conditions:
      - base=master
      - label=speculative-merge
    actions:
      queue:
        name: speculative
  - name: automatic update for PRs to be merged
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label=speculative-merge
    actions:
      update:

merge_queue:
  max_parallel_checks: 5
