queue_rules:
  - name: speculative
    speculative_checks: 5
    conditions: []

pull_request_rules:
  - name: merge speculatively
    conditions:
      - base=master
      - label=speculative-merge
    actions:
      queue:
        name: speculative
